import java.util.Arrays;

/**
 * Created by tilz on 03/03/2017.
 *
 * Searches text for wakeword
 */


public class SearchText{
    /**
     * This is a method which searches the string of text and returns a
     * boolean if the wakeword is found and splits the string use the
     * wakeword as the splitter, anything after wakeword is interpreted
     * as the question.
     *
     * @param text  text is generated by the sound recording transformed into text
     * @return found  returns a boolean to say weather the wakeword was found or not
     */
    static boolean findWakeWord (String text ){
        String WakeWord = "Alexa";
        boolean found = Arrays.asList(text.split(" ")).contains(WakeWord);
        if(found){
            System.out.println("wakeword found");
            String [] parts = text.split(WakeWord); //splits text into two parts, the part before wake word and the part after
            String question = parts[1]; // defines part after wakeword as the question
            System.out.println(question);
            //enter text after wakeword into wolfram alpha
        }
        else{
            //keep listening
        }
        return found;
    }


    public static void main (String[] argv){
        findWakeWord("Alexa what is the melting point of silver");

    }

}