import java.util.Arrays;

/**
 * Created on 03/03/2017.
 *
 * Searches text for wakeword
 */


public class SearchText{
    /**
     * This is a method which searches the string of text and returns a
     * boolean if the wakeword is found and splits the string use the
     * wakeword as the splitter, anything after wakeword is interpreted
     * as the question.
     *
     * @param text  text is generated by the sound recording transformed into text
     * @return question
     */
    static String findWakeWord (String text ) {
        String WakeWord = "echo";
        if(Arrays.asList(text.split(" ")).contains(WakeWord)) {
            return "Echo";
        } else {
            return null;
        }
    }

    public static void main (String[] argv){
        findWakeWord("Echo what is the melting point of silver");
    }


}
